name: stat application class

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - name: Set up Java Environment
      - uses: actions/setup-python@v2
        with:
          java-version: '18'
        run: |
          cd ./src
          javac registerComponent.java